import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { ReactNode } from "react";
import CharacterList from "@/components/CharactersList";
import {
  CharacterType,
  fetchCharacters,
} from "@/components/services/servicesCharacters";

export const getStaticProps: GetStaticProps = async () => {
  const characters = await fetchCharacters();

  return { props: { characters } };
};

const Home: NextPage = (props: {
  children?: ReactNode;
  characters?: CharacterType[];
}) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>

      <main>{<CharacterList characters={props.characters!} />}</main>
    </>
  );
};

export default Home;
